version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  api:
    build: ./backend
    ports:
      - 5000:5000
      env_file:
        - ./backend/env.sh
    volumes:
      - ./backend:/app
  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - boilerplate:/data/db

volumes:
  boilerplate:
